student:
  id: ""                # 学号
  pwd: ""               # 密码

preferred_time_list:                # 期望时间，以如示例格式给出
  - ['16:00-17:00', '17:00-18:00']  # 表示两个小时连起来
  - ['20:00-21:00', '21:00-22:00']
  - ['19:00-20:00']                 # 表示一个小时，不要漏掉方框
expected_stadium: "主馆" # 场馆选择："主馆"|"副馆"|"沙河"

buddy:                  # 同伴
  override: False       # 如果为 True，则强制删除所有同伴，新增一个同伴；否则，如果没有同伴，就新增一个同伴。
  id: ""                # 同伴学号，建议填上，不论 override 的值为多少。

cjy:                    # 验证码平台相关信息
  username: ""          # 账户
  password: ""          # 密码，md5-32位小写形式
  softid: ""            # 软件KEY

ip: # 代理ip平台相关信息 如果没有被封禁，建议不要开启；否则可以注册快代理（https://www.kuaidaili.com/）等平台使用代理IP。
  enable: False
  api_url: ""
  username: ""
  password: ""

snap_up_mode: True      # 是否为抢场模式，仅用于测试，无需更改。
debug_mode: False       # 是否为调试模式，为 True 时可以看到操作界面。
timer: True             # 是否打开计时器，可以检测抢场总用时时长。
